"""
Django settings for datalist project.

Generated by 'django-admin startproject' using Django 2.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'so3j)+3vy3(h%!_7u6&ixd=p%k8tyc%8-b$(4lbio$wlb^z+5h'

# SECURITY WARNING: don't run with debug turned on in production!
#2020.06.10  在本机测试时用True
DEBUG = True
ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'user',
    'first',
    'sscCq',
    'sscXj',
    'sscTj',
    'sscHn',
    'gd11x5',
    'bjpk10',
    'Azxy10',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # 使用中文
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'datalist.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates'),
                 os.path.join(BASE_DIR,'first/templates'),
                 os.path.join(BASE_DIR,'sscCq/templates'),
                 os.path.join(BASE_DIR,'sscTj/templates'),
                 os.path.join(BASE_DIR,'sscXj/templates'),
                 os.path.join(BASE_DIR,'gd11x5/templates'),
                 os.path.join(BASE_DIR,'bjpk10/templates'),
                 os.path.join(BASE_DIR,'Azxy10/templates'),
                 os.path.join(BASE_DIR,'user/templates'),
                 os.path.join(BASE_DIR,'sscHn/templates'),
                 ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'datalist.wsgi.application'


# Database   'HOST': '106.55.162.249',
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME':  'music_db',
        'USER':  'root',
        'PASSWORD': 'SHuyang970819!$',
        'HOST': '106.55.162.249',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE ='Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


#  配置邮件服务器发送邮件采用smtp服务
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
# 使用tls方式
EMAIL_USE_TLS = False
#发送邮件的服务器为163邮箱
EMAIL_HOST = "smtp.163.com"
# 因为采用的是非SSL协议，所以端口是25
EMAIL_PORT = 25
#邮件的发送者邮箱
EMAIL_HOST_USER = "zhangchunyang199@163.com"
#EMAIL_HOST_PASSWORD = "rfvwkpcsxdvvbgif"    #370189979 de
#在163邮件网页用手机开通授权码
EMAIL_HOST_PASSWORD = "TFOIQLDSLBNVHBMP"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

# 配置自定义用户表MyUser
AUTH_USER_MODEL = 'user.MyUser'

STATIC_URL = '/static/'
#STATIC_ROOT = os.path.join(BASE_DIR,'allstatic')
#STATIC_ROOT = '/home/datalist/static/' #在远程服务器上用的静态文件路径
STATIC_ROOT = 'datalist/static/'     # 在本机测试用的静态文件路径

STATICFILES_DIRS = [os.path.join(BASE_DIR,'static')]
